export const districtCityMap = {
    Ampara: ["Ampara", "Kalmunai", "Sainthamaruthu", "Akkaraipattu", "Sammanthurai"],
    Anuradhapura: ["Anuradhapura", "Kekirawa", "Mihintale", "Thambuttegama", "Medawachchiya"],
    Badulla: ["Badulla", "Bandarawela", "Ella", "Haputale", "Mahiyanganaya"],
    Batticaloa: ["Batticaloa", "Eravur", "Kattankudy", "Valaichchenai", "Kaluvanchikudy"],
    Colombo: ["Colombo", "Dehiwala", "Moratuwa", "Kotte", "Maharagama"],
    Galle: ["Galle", "Hikkaduwa", "Ambalangoda", "Elpitiya", "Karapitiya"],
    Gampaha: ["Gampaha", "Negombo", "Kelaniya", "Wattala", "Ja-Ela"],
    Hambantota: ["Hambantota", "Tangalle", "Beliatta", "Tissamaharama", "Weeraketiya"],
    Jaffna: ["Jaffna", "Nallur", "Chavakachcheri", "Kopay", "Karainagar"],
    Kalutara: ["Kalutara", "Beruwala", "Panadura", "Horana", "Matugama"],
    Kandy: ["Kandy", "Peradeniya", "Katugastota", "Gampola", "Nawalapitiya"],
    Kegalle: ["Kegalle", "Mawanella", "Warakapola", "Ruwanwella", "Yatiyanthota"],
    Kilinochchi: ["Kilinochchi", "Paranthan", "Mankulam", "Pallai", "Iranamadu"],
    Kurunegala: ["Kurunegala", "Kuliyapitiya", "Nikaweratiya", "Mawathagama", "Polgahawela"],
    Mannar: ["Mannar", "Murunkan", "Pesalai", "Madhu", "Thiruketheeswaram"],
    Matale: ["Matale", "Dambulla", "Galewela", "Rattota", "Ukuwela"],
    Matara: ["Matara", "Weligama", "Hakmana", "Dikwella", "Devinuwara"],
    Monaragala: ["Monaragala", "Wellawaya", "Bibile", "Buttala", "Medagama"],
    Mullaitivu: ["Mullaitivu", "Puthukudiyiruppu", "Oddusuddan", "Maritimepattu", "Vavunathivu"],
    NuwaraEliya: ["Nuwara Eliya", "Hatton", "Ginigathhena", "Talawakele", "Kotmale"],
    Polonnaruwa: ["Polonnaruwa", "Hingurakgoda", "Medirigiriya", "Kaduruwela", "Welikanda"],
    Puttalam: ["Puttalam", "Chilaw", "Wennappuwa", "Anamaduwa", "Nattandiya"],
    Ratnapura: ["Ratnapura", "Balangoda", "Embilipitiya", "Pelmadulla", "Opanayaka"],
    Trincomalee: ["Trincomalee", "Kinniya", "Muttur", "Kantale", "Uppuveli"],
    Vavuniya: ["Vavuniya", "Cheddikulam", "Nedunkeni", "Omanthai", "Vavunathivu"],
  };
  